name: Debug Secrets

on:
  push:
    branches:
      - main

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Check Username
        run: |
          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
            echo "USERNAME EMPTY"
          else
            echo "USERNAME OK"
          fi

      - name: Check Password
        run: |
          if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
            echo "PASSWORD EMPTY"
            exit 1
          else
            echo "PASSWORD OK"
          fi